customhost = "database-1.c5kkmgndrvtk.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leongjingxuan-employee1"
customregion = "us-east-1"
